### PR TITLE
Update Gradle to 5.6

### PR DESCRIPTION
**Pull request by zegnus**
- Upgrade Gradle to [5.6](https://docs.gradle.org/5.6/release-notes.html)

This solves https://github.com/novoda/gradle-static-analysis-plugin/issues/168

### CODE REVIEW

**Comment by mr-archano** [comment]
@zegnus the CI is not happy about the change. Could you please look into it and let us know what is the problem?

**Comment by zegnus** [comment]
@mr-archano the CI runs out of memory... I honestly do not know how to fix this :(

**Comment by mr-archano** [comment]
@zegnus have you tried with this? https://docs.gradle.org/current/userguide/build_environment.html#sec:configuring_jvm_memory

Gradle 5.x has changed the amount of memory allocated by default to the daemon. It could be also worth be explicit in the amount of memory assigned to the test process (see https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html)

**Comment by tasomaniac** [comment]
Superseeded by #203

**Pull request closed without merging**
