### PR TITLE
Update PMD docs to have incremental

### LINKED ISSUE #104: PMD incremental analysis
I am not sure if this plugin already provide any functionality in this direction, but PMD shows me the message to turn the Incremental Analysis on for a higher performance.

https://pmd.github.io/pmd-6.3.0/pmd_userdocs_getting_started.html#incremental-analysis

Is there a solution for this yet?

### PR DESCRIPTION
**Pull request by tasomaniac**
Fixes #104

### CODE REVIEW

**Comment by mr-archano** [comment]
@tasomaniac shouldn't this be against `develop` to avoid issues?

**Comment by tasomaniac** [comment]
If we merge it soon, it makes no difference but usually docs changes go to master since they should be taken into account immediately.

**Comment by mr-archano** [comment]
Ok, we will need to merge `master` into `develop` after this.

**Comment by tasomaniac** [comment]
You can just use `Update Branch` in https://github.com/novoda/gradle-static-analysis-plugin/pull/215. There are actually more commits in master.

**Pull request merged**
